### ISSUE TITLE
"Network Error!" issue.

### ISSUE THREAD

**Issue by paulallenfromap** [DestinationHome/PlayStation-Home-Hen-Offline#2]
https://user-images.githubusercontent.com/94869776/145725984-be052c12-5a17-4036-9e2b-81e2cdfd24ab.mp4

**Comment by NagatoDEV** [comment]
Hi Paul! Did you make sure to hit `Offline` and not online? Plus what build version are you using.

**Comment by paulallenfromap** [comment]
hello, i pressed offline and the build version is 0.2 i think.
