### ISSUE TITLE
Destination Home 1.86 Offline PS3 Client 2.00 Full Client + HEN

### ISSUE THREAD

**Issue by dmitryb0** [DestinationHome/PlayStation-Home-Hen-Offline#3]
HI!
Is there any possibility to use together "Destination Home 1.86 Offline PS3 Client 2.00 Full Client" - https://drive.google.com/drive/folders/1y5LZYsCmCx1cKteV9J5l1RjUQvzzPJ6B?usp=sharing & "PlayStation®Home Developer | HEN-QA Launcher" ??
Thanks!

**Comment by wpnsrus** [comment]
> HI! Is there any possibility to use together "Destination Home 1.86 Offline PS3 Client 2.00 Full Client" - https://drive.google.com/drive/folders/1y5LZYsCmCx1cKteV9J5l1RjUQvzzPJ6B?usp=sharing
+ "PlayStation®Home Developer | HEN-QA Launcher" ??
Thanks!

**Comment by dmitryb0** [comment]
aayy 
hey, friends?! help me
